name: flutter_document_scanner_android
description: Android implementation of the flutter_document_scanner plugin
repository: https://github.com/criistian14/flutter_document_scanner/tree/master/flutter_document_scanner_android
version: 1.1.1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: flutter_document_scanner
    platforms:
      android:
        package: com.christian.flutterDocumentScanner
        pluginClass: FlutterDocumentScannerPlugin
        dartPluginClass: FlutterDocumentScannerAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_document_scanner_platform_interface:
    path: "/Users/nige.karus/GitHubDev/flutter_document_scanner_nowarp/flutter_document_scanner_platform_interface"
  native_device_orientation: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.1
