name: flutter_document_scanner_ios
description: iOS implementation of the flutter_document_scanner plugin
repository: https://github.com/criistian14/flutter_document_scanner/tree/master/flutter_document_scanner_ios
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: flutter_document_scanner
    platforms:
      ios:
        pluginClass: FlutterDocumentScannerPlugin
        dartPluginClass: FlutterDocumentScannerIOS

dependencies:
  flutter:
    sdk: flutter
  flutter_document_scanner_platform_interface:
    path: "/Users/nige.karus/GitHubDev/flutter_document_scanner_nowarp/flutter_document_scanner_platform_interface"
  native_device_orientation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.1
